### basic settings

# site properties and page defaults
title: DePasquale Lab
description: My lab website
logo: images/pone.0191527.g001.png
#header: images/background.jpg
footer: images/pone.0191527.g001.png
baseurl: ""

# site social media and other links
links:
  email: bddepasqh@bu.edu
  google-scholar: Brian DePasquale
  github: depasquale-lab
  #twitter: YourLabHandle
  #instagram: YourLabHandle
  #youtube: YourLabChannel

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
